"""Independent exploratory $50/$5 taker paper session. No account/order APIs."""
import asyncio
from collections import Counter
import hashlib
import json
import math
import time
from pathlib import Path
from websockets.asyncio.client import connect
import httpx
from .directional import Journal, probability, read_journal
from .five_minute_live import parse_contract, final_winner
from .daily_readiness import fee_match
from .daily_capture import book_status
from .ntp_probe import diagnostic
from .journal_lifecycle import stop_producers
from .reference_transport import consume, load_transport_policy, wait_for_reference, POLICY_SHA as TRANSPORT_SHA, FREEZE_COMMIT as TRANSPORT_FREEZE

POLICY_SHA = '5efae6c98d14469597bec251035e3d4da6cc3378870130291fedf2c3ebf1228d'
FREEZE_COMMIT = '5ae48e693ce8ede9f66e39d0c565d0659c3565bb'
RULE_TEXT = 'This market will resolve to "Up" if the time-weighted average price (TWAP) of Bitcoin, generated by Chainlink, of the time range specified in the title is greater than or equal to the price at the beginning of that range. Otherwise, it will resolve to "Down".'


def load_policy():
    raw=(Path(__file__).resolve().parents[1]/'docs/unified/policy.json').read_bytes()
    if hashlib.sha256(raw).hexdigest()!=POLICY_SHA: raise ValueError('Frozen unified policy changed')
    return json.loads(raw)


def quote_budget(book, token, limit, rate, budget=5):
    """Conditional visible-depth FOK cash budget, fees conservatively rounded up."""
    if not all(math.isfinite(v) for v in (limit,rate,budget)) or not 0<limit<1 or not 0<=rate<1 or budget<=0:
        raise ValueError('Invalid budget, limit or fee')
    if book_status(book,token)!='two_sided': raise ValueError('Invalid two-sided book')
    remaining=budget; shares=notional=fees=0.; consumed=[]
    for level in sorted(book['asks'],key=lambda x:float(x['price'])):
        p,size=float(level['price']),float(level['size'])
        if p>limit: break
        quantity=min(size,remaining/(p+rate*p*(1-p)))
        quantity=math.floor(quantity*1e6)/1e6
        fee=math.ceil(quantity*rate*p*(1-p)*1e5)/1e5
        if quantity*p+fee>remaining:
            quantity=max(0,math.floor((remaining-1e-5)/(p+rate*p*(1-p))*1e6)/1e6)
            fee=math.ceil(quantity*rate*p*(1-p)*1e5)/1e5
        if quantity<=0: continue
        cost=quantity*p+fee
        if cost>remaining+1e-10:raise ValueError('Fee rounding exceeds cash budget')
        remaining-=cost; shares+=quantity; notional+=quantity*p; fees+=fee
        consumed.append({'price':p,'shares':quantity,'fee_usd':fee})
        if remaining<.0001:break
    if remaining>=.0001 or shares<float(book.get('min_order_size',5)):
        raise ValueError('Entire $5 budget or minimum shares unavailable under limit')
    return {'shares':shares,'principal_usd':notional,'entry_fee_usd':fees,
            'cost_usd':notional+fees,'levels':consumed,'assumption':'CONDITIONAL_DISPLAYED_TAKER_DEPTH_NOT_ACTUAL_EXECUTION'}


class Ledger:
    def __init__(self):self.cash=50.;self.positions=[];self.settled=[];self.equity=[50.]
    def open(self,cid,side,quote,market,now):
        if any(not p.get('settled') for p in self.positions) or self.cash+1e-8<quote['cost_usd'] or any(p['condition_id']==cid for p in self.positions):
            raise ValueError('Open position, duplicate market or insufficient cash')
        if side not in ('Up','Down') or not 0<quote['cost_usd']<=5 or quote['shares']<=0:
            raise ValueError('Invalid paper entry')
        self.cash-=quote['cost_usd']
        row={'condition_id':cid,'side':side,'market':market,'opened_at':now,**quote,'settled':False,
             'fully_net_pnl_after_other_costs':None,'source_match_status':'PENDING'}
        self.positions.append(row);return row
    def settle(self,cid,winner,now):
        if winner not in ('Up','Down'):raise ValueError('Invalid winner')
        p=next((x for x in self.positions if x['condition_id']==cid and not x['settled']),None)
        if p is None:return None
        payout=p['shares'] if winner==p['side'] else 0.
        self.cash+=payout
        p.update(settled=True,winner=winner,settled_at=now,payout_usd=payout,
                 simulated_pnl_after_entry_taker_fee=payout-p['cost_usd'])
        self.settled.append(p);self.equity.append(self.cash);return p
    def report(self):
        peak=50.;drawdown=0.
        for e in self.equity:peak=max(peak,e);drawdown=max(drawdown,peak-e)
        return {'starting_cash_usd':50,'cash_usd':self.cash,'paper_trades':len(self.positions),
            'settled_trades':len(self.settled),'pending_positions':[p for p in self.positions if not p['settled']],
            'simulated_pnl_after_entry_taker_fees_settled_only':sum(p['simulated_pnl_after_entry_taker_fee'] for p in self.settled),
            'wins':sum(p['winner']==p['side'] for p in self.settled),
            'losses':sum(p['winner']!=p['side'] for p in self.settled),
            'source_verified_settled_trades':sum(p['source_match_status']=='MATCHED' for p in self.settled),
            'source_verified_simulated_pnl_after_entry_fees':sum(p['simulated_pnl_after_entry_taker_fee'] for p in self.settled if p['source_match_status']=='MATCHED'),
            'source_invalid_trade_count':sum(p['source_match_status']=='MISMATCH_INVALID' for p in self.positions),
            'source_pending_trade_count':sum(p['source_match_status']=='PENDING' for p in self.positions),
            'max_drawdown_settled_equity_usd':drawdown,'total_net_pnl_after_all_costs':None,
            'other_costs_usd':None,'actual_orders':0,'actual_fills':0}


class Feed:
    def __init__(self,journal):self.series={'spot':{},'twap':{}};self.journal=journal;self.generation=0
    def ingest(self,message,received):
        if not isinstance(message,dict):return
        payload=message.get('payload')
        if not isinstance(payload,dict) or payload.get('symbol')!='btc/usd':return
        kind={'crypto_prices_chainlink':'spot','crypto_prices_twap_sixty':'twap'}.get(message.get('topic'))
        # Generic crypto_prices snapshots are not proven Chainlink spot.
        if kind is None:return
        if kind=='twap' and payload.get('window_s',60)!=60:return
        entries=payload.get('data') if isinstance(payload.get('data'),list) else [payload]
        for e in entries:
            try:
                ts=float(e['timestamp'])/1000;value=float(e['value'])
                if not math.isfinite(ts+value) or value<=0 or ts>received+2:continue
                existing=self.series[kind].get(ts)
                if existing and existing['price']!=value:
                    self.generation+=1;self.journal.write({'type':'reference_revision','kind':kind,'timestamp':ts,'old':existing,'new':e})
                    continue
                self.series[kind].setdefault(ts,{'timestamp':ts,'price':value,'received_at':received,'generation':self.generation})
            except (KeyError,ValueError,TypeError):continue
        self.series[kind]={t:v for t,v in self.series[kind].items() if t>=received-1200}
    async def run(self):
        transport=load_transport_policy()
        while True:
            ws=None
            try:
                async with connect('wss://ws-live-data.polymarket.com',proxy=None,open_timeout=8,ping_interval=10,max_queue=128) as ws:
                    self.generation+=1
                    self.journal.write({'type':'feed_open','generation':self.generation,'at':time.time(),'transport_policy_sha256':TRANSPORT_SHA})
                    result=await consume(ws,self.journal,self.ingest,transport)
                    if result=='AUTH_REQUIRED':return
            except asyncio.CancelledError:raise
            except Exception as exc:
                self.generation+=1
                self.journal.write({'type':'feed_gap','at':time.time(),'error':str(exc),'error_type':type(exc).__name__,'generation':self.generation})
            finally:
                if ws is not None:self.journal.write({'type':'feed_close','at':time.time(),'code':getattr(ws,'close_code',None),'reason':getattr(ws,'close_reason',None),'generation':self.generation})
            await asyncio.sleep(transport['reconnect_delay_seconds'])
    def features(self,start,now,policy):
        opening=self.series['twap'].get(start)
        if not opening or not start<=opening['received_at']<=start+2:
            raise ValueError('MISSING_CAUSAL_EXACT_TWAP_OPENING')
        history=[v for t,v in sorted(self.series['spot'].items()) if now-120<=t<=now]
        if len(history)<61 or history[0]['timestamp']>now-118:
            raise ValueError('MISSING_MATCHED_CHAINLINK_SPOT_HISTORY')
        latest=history[-1]
        if not 0<=now-latest['timestamp']<=2 or not 0<=time.time()-latest['received_at']<=2:
            raise ValueError('STALE_UNDERLYING_REFERENCE')
        if opening['generation']!=self.generation or any(v['generation']!=self.generation for v in history):
            raise ValueError('REFERENCE_CONNECTION_GAP_OR_REVISION')
        total=elapsed=0.
        for a,b in zip(history,history[1:]):
            gap=b['timestamp']-a['timestamp']
            if not 0<gap<=2:raise ValueError('REFERENCE_HISTORY_GAP')
            total+=math.log(b['price']/a['price'])**2;elapsed+=gap
        if total<=0:raise ValueError('ZERO_VOLATILITY')
        sigma=math.sqrt(total/elapsed)*latest['price']
        p=probability(latest['price'],opening['price'],sigma,latest['timestamp'],start+300,'twap',60)
        return {'p_up':p,'opening':opening,'latest':latest,'intervals':len(history)-1,'sigma_price_per_sqrt_second':sigma}


async def session(output,policy,*,duration_seconds=None,execution_plan=None,stop_at=None):
    duration=policy['duration_seconds'] if duration_seconds is None else duration_seconds
    if not isinstance(duration,int) or isinstance(duration,bool) or duration<=0:
        raise ValueError('Invalid session duration')
    started=time.time();started_mono=time.monotonic()
    if stop_at is not None:
        if isinstance(stop_at,bool) or not isinstance(stop_at,(int,float)) or not math.isfinite(stop_at) or stop_at<=started:
            raise ValueError('Invalid or elapsed absolute session deadline')
        if duration_seconds is not None:raise ValueError('Choose duration or absolute deadline, not both')
        duration=stop_at-started
    output=Path(output);output.mkdir(parents=True,exist_ok=False)
    first=(int(started//300)+1)*300;stop=started+duration if stop_at is None else stop_at
    windows=list(range(first,int(stop-300)+1,300))
    journal=Journal(output/'journal.jsonl',{'mode':'INDEPENDENT_EXPLORATORY_PAPER','policy_sha256':POLICY_SHA,
        'freeze_commit':FREEZE_COMMIT,'transport_policy_sha256':TRANSPORT_SHA,'transport_freeze_commit':TRANSPORT_FREEZE,'started_at':started,'predeclared_windows':windows,
        'bankroll_usd':50,'trade_budget_usd':5,'actual_orders':0,'other_costs_usd':None,
        'planned_duration_seconds':duration,'stop_entry_at':stop,'execution_plan':execution_plan})
    feed=Feed(journal);ledger=Ledger();decisions=[];roster={};anchors={};source_mismatch=False
    clock=None;reasons=Counter();fetched=set();decided=set();audited=set();done=False
    async with httpx.AsyncClient(timeout=2,trust_env=False,follow_redirects=False) as client:
        async def get(url,params=None,role=None):
            row={'type':'http','url':url,'params':params,'role':role,'sent_at':time.time()};mono=time.monotonic()
            try:
                r=await client.get(url,params=params);received=time.time()
                row.update(received_at=received,wall_elapsed_seconds=received-row['sent_at'],rtt_seconds=time.monotonic()-mono,status=r.status_code,body_sha256=hashlib.sha256(r.content).hexdigest())
                r.raise_for_status();row['data']=r.json()
            except Exception as exc:row.update(error=str(exc),received_at=time.time())
            journal.write(row);return row
        async def clocks():
            nonlocal clock
            while True:
                clock=await asyncio.to_thread(diagnostic,{'maximum_clock_uncertainty_seconds':.5})
                journal.write({'type':'clock','data':clock});await asyncio.sleep(60)
        def corrected_now():
            if not clock or not clock['all_samples_within_frozen_bound'] or not clock['intervals_consistent']:
                raise ValueError('CLOCK_UNVERIFIED')
            sample=clock['samples'][-1]
            if time.time()-sample['observed_at']>90:raise ValueError('CLOCK_STALE')
            return time.time()+sample['offset_seconds'],clock['worst_uncertainty_seconds']
        def fresh(row,now):
            if 'error'in row or not 0<=now-row['received_at']<=2 or row['rtt_seconds']>2 or abs(row['wall_elapsed_seconds']-row['rtt_seconds'])>.001:
                raise ValueError('HTTP_FAILED_STALE_OR_SLOW')
        async def meta(start):
            slug=f'btc-updown-5m-{start}'
            r=await get('https://gamma-api.polymarket.com/events',{'slug':slug},'metadata')
            event=next((e for e in r.get('data',[]) if e.get('slug')==slug),None)
            if event is None:raise ValueError('MARKET_METADATA_UNAVAILABLE')
            raw=next((m for m in event.get('markets',[]) if m.get('slug')==slug),None)
            if raw is None:raise ValueError('MARKET_METADATA_UNAVAILABLE')
            return raw,event,r
        async def reconcile(now):
            nonlocal source_mismatch
            for start,raw in list(roster.items()):
                if now<start+310 or start in audited or start not in anchors:continue
                try:
                    _,event,_=await meta(start)
                    official=(event.get('eventMetadata')or{}).get('priceToBeat')
                    anchor=anchors.get(start)
                    if official is not None and anchor is not None:
                        match=abs(float(official)-anchor['price'])<=1e-6
                        journal.write({'type':'source_match_audit','start':start,'official_opening':official,'recorded_opening':anchor,'match':match})
                        audited.add(start)
                        for p in ledger.positions:
                            if p['market']['start']==start:p['source_match_status']='MATCHED' if match else 'MISMATCH_INVALID'
                        if not match:source_mismatch=True
                except (KeyError,TypeError,ValueError,StopIteration) as exc:journal.write({'type':'audit_pending','start':start,'error':str(exc)})
            pending=[p for p in ledger.positions if not p['settled'] and now>=p['market']['end']+10]
            for p in pending:
                row=await get('https://data-api.polymarket.com/v2/resolutions',{'condition':p['condition_id']},'resolution')
                for state in (row.get('data')or{}).get('data',[]):
                    winner=final_winner(state,p['market']['raw'],p['market']['end'],row['received_at'])
                    if winner:
                        settled=ledger.settle(p['condition_id'],winner,row['received_at'])
                        if settled:journal.write({'type':'paper_settlement','position':settled})
        tasks=[asyncio.create_task(feed.run()),asyncio.create_task(clocks())]
        last_reconcile=0
        def checkpoint(final=False,error=None):
            report={'mode':'INDEPENDENT_EXPLORATORY_PAPER','policy_sha256':POLICY_SHA,'freeze_commit':FREEZE_COMMIT,
                'started_at':started,'updated_at':time.time(),'elapsed_seconds':time.time()-started,
                'planned_duration_seconds':duration,'elapsed_monotonic_seconds':time.monotonic()-started_mono,
                'execution_plan':execution_plan,'stop_entry_at':stop,'complete':final,'predeclared_market_count':len(windows),
                'decisions':decisions,'reason_counts':dict(reasons),'ledger':ledger.report(),
                'all_trades':ledger.positions,'source_mismatch':source_mismatch,
                'audited_opening_count':len(audited),'full_decision_count':len(windows),
                'descriptive_model_decision_count':sum(d.get('p_up')is not None for d in decisions),
                'profitability_proven':False,'financial_go':False,'old_protocol_effect':'NONE','error':error}
            clean=sum(d.get('data_admitted',False) for d in decisions)
            report['descriptive_clean_sampled_windows']={'count':clean,'full_count':len(windows),
                'excluded_window_fraction':1-clean/len(windows) if windows else None,
                'scope':'Whole scheduled 300-second windows classified only at fixed decision; not continuous clean seconds or protocol admission',
                'equivalent_excluded_window_seconds':(len(windows)-clean)*300,
                'decisions':[d for d in decisions if d.get('data_admitted',False)]}
            tmp=output/'summary.tmp';tmp.write_text(json.dumps(report,indent=2,allow_nan=False)+'\n');tmp.replace(output/'summary.json')
            return report
        try:
            checkpoint()
            print(json.dumps({'event':'session_started','started_at':started,'stop_at':stop,'market_count':len(windows),'policy_sha256':POLICY_SHA,'bankroll':50,'trade_budget':5,'actual_orders':0}),flush=True)
            while time.time()<stop+policy['drain_seconds']:
                now=time.time()
                # Fetch at most one immutable roster per predeclared window.
                for start in windows:
                    if start-20<=now<=start+20 and start not in fetched:
                        fetched.add(start)
                        try:
                            raw,event,r=await meta(start);tokens=parse_contract(raw,start)
                            if not raw.get('description','').startswith(RULE_TEXT) or raw.get('resolutionSource')!='https://data.chain.link/streams/btc-usd-twap-60s-streams' or (raw.get('cryptoMarketConfig')or{}).get('twapLookbackSeconds')!=60:
                                raise ValueError('UNKNOWN_SETTLEMENT_RULE_OR_STREAM')
                            fee=await get('https://clob.polymarket.com/clob-markets/'+raw['conditionId'],role='fees')
                            if not fee_match(raw,fee.get('data'),list(tokens.values())):raise ValueError('FEE_OR_TOKEN_MISMATCH')
                            roster[start]=raw;raw['_paper_tokens']=tokens;raw['_paper_rate']=float(fee['data']['fd']['r'])
                            journal.write({'type':'market_roster','start':start,'raw':raw,'metadata_received_at':r['received_at']})
                        except (KeyError,TypeError,ValueError,StopIteration)as exc:reasons[str(exc)]+=1
                    if start+180<=now and start not in decided:
                        decided.add(start);d={'type':'decision','start':start,'created_at':time.time(),'choice':'ABSTAIN','p_up':None,'reason':None}
                        try:
                            corrected,width=corrected_now()
                            if abs(corrected-(start+180))+width>2:raise ValueError('MISSED_FIXED_DECISION_WINDOW')
                            if now>=stop:raise ValueError('ENTRY_PERIOD_ENDED')
                            if source_mismatch:raise ValueError('SOURCE_MISMATCH_STOPPED')
                            raw=roster[start];features,corrected=await wait_for_reference(feed,start,corrected_now,policy);d.update(features);d['features_at']=corrected
                            anchors[start]=features['opening']
                            if any(not p['settled'] for p in ledger.positions):raise ValueError('OPEN_POSITION_LIMIT')
                            if ledger.cash<5:raise ValueError('INSUFFICIENT_BANKROLL')
                            tokens=raw['_paper_tokens'];rate=raw['_paper_rate']
                            pair=await asyncio.gather(*(get('https://clob.polymarket.com/book',{'token_id':tokens[o]},'decision_book')for o in ('Up','Down')))
                            wall=time.time()
                            for row in pair:fresh(row,wall)
                            if max(r['received_at']for r in pair)-min(r['received_at']for r in pair)>2:raise ValueError('BOOK_PAIR_SKEW')
                            choices=[]
                            for side,row in zip(('Up','Down'),pair):
                                book=row['data']
                                if book_status(book,tokens[side])!='two_sided':continue
                                ask=min(float(x['price'])for x in book['asks']);limit=ask+.005
                                if limit>=1:continue
                                try:q=quote_budget(book,tokens[side],limit,rate)
                                except ValueError:continue
                                # Reserve full slippage allowance in the signal edge.
                                p=features['p_up'] if side=='Up' else 1-features['p_up']
                                edge=p-q['cost_usd']/q['shares']-.005
                                choices.append((edge,side,limit,q))
                            if not choices:raise ValueError('NO_TWO_SIDED_DEPTH')
                            d['data_admitted']=True
                            choices.sort(key=lambda x:(-x[0],x[1]));edge,side,limit,q=choices[0]
                            d.update(informational_edge=edge,requested_side=side,limit=limit)
                            if edge<.03:raise ValueError('NO_SUFFICIENT_EDGE')
                            journal.write({'type':'paper_intent','start':start,'side':side,'budget_usd':5,'limit':limit,'features':features,'at':time.time()})
                            await asyncio.sleep(.5+max(0,corrected-features['latest']['timestamp']))
                            refreshed=await get('https://clob.polymarket.com/book',{'token_id':tokens[side]},'execution_book')
                            fresh(refreshed,time.time())
                            if time.time()>=start+300:raise ValueError('WINDOW_ENDED_BEFORE_RECHECK')
                            newfeatures=feed.features(start,corrected_now()[0],policy)
                            newp=newfeatures['p_up'] if side=='Up' else 1-newfeatures['p_up']
                            execution=quote_budget(refreshed['data'],tokens[side],limit,rate)
                            if newp-execution['cost_usd']/execution['shares']-.005<.03:raise ValueError('EDGE_LOST_BEFORE_RECHECK')
                            position=ledger.open(raw['conditionId'],side,execution,{'start':start,'end':start+300,'slug':raw['slug'],'raw':raw},time.time())
                            d.update(choice=side,reason='CONDITIONAL_PAPER_TAKER_FILL',execution=execution)
                            journal.write({'type':'paper_fill','position':position})
                        except (KeyError,TypeError,ValueError)as exc:d['reason']=str(exc);reasons[str(exc)]+=1
                        journal.write(d);decisions.append(d);checkpoint()
                        print(json.dumps({'event':'decision','start':start,'choice':d['choice'],'reason':d['reason'],'paper_trades':len(ledger.positions),'cash_usd':ledger.cash}),flush=True)
                if now-last_reconcile>=30:
                    await reconcile(now);last_reconcile=time.time();checkpoint()
                if now>=stop and not any(not p['settled']for p in ledger.positions):break
                await asyncio.sleep(.1)
            # Missing windows remain explicit in all-session denominator.
            for start in windows:
                if start not in decided:
                    d={'start':start,'choice':'ABSTAIN','p_up':None,'reason':'MISSING_SCHEDULED_DECISION'}
                    decisions.append(d);journal.write({'type':'decision',**d})
            await stop_producers(tasks)
            final=checkpoint(True);journal.write({'type':'complete','finished_at':time.time(),'actual_orders':0});done=True
            print(json.dumps({k:v for k,v in final.items()if k not in ('decisions','all_trades')}))
        except BaseException as exc:
            checkpoint(False,str(exc));journal.write({'type':'session_failed','error':str(exc),'at':time.time()});raise
        finally:
            try:await stop_producers(tasks)
            finally:journal.close()
    if done:list(read_journal(output/'journal.jsonl'))


if __name__=='__main__':asyncio.run(session('runs/unified-four-hour',load_policy()))
